name: bazzite-mechrevo
description: Default Bazzite met Motorcomm YT6801 LAN driver.

base-image: ghcr.io/ublue-os/bazzite
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  # yt6801 driver for mechrevo
  - type: script
    scripts:
      - build-yt6801.sh

